
export const path = {
    PUBLIC: "/",
    HOME: "/",
    ALL: "*",
    LOGIN: "/login",
    BLOG: "/blogs",
    BLOG_DETAIL: ":bid",
    OUT_SERVICER: "servicer",
    FAQ: "faqs",
    CONTACT: "lien-he",
    DETAIL_PRODUCT_CATEGORI_PID_TITLE: ":cid/:pid/:title",
    DETAIL_PRODUCT: "san-pham",
    FINAl_REGISTER: "finalRegister/:status",
    RESET_PASSWORD: "reset-password/:token",
    PROFILE: "profile",
    PRODUCTCA: "/:category",
    DETAILCART: "detailCart",
    CHECKOUT: "checkout",

    // admin
    ADMIN: "/admin",
    DASHBOARD: "dashboard",
    MANAGER_PRODUCT: "manager-product",
    MANAGER_USER: "manager-user",
    MANAGER_ORDER: "manager-order",
    CREATE_PRODUCT: "create-product",
    MANAGER_BLOG: "manager-blog",
    // member
    MEMBER: "/member",
    WISHLIST: "wishlist",
    HISTORY: "history",
    MYCART: "mycart",
    PERSONAL: "personal",
    BLOG_USER: "blog_user",
}
