export { default as Header } from "./header/header"
export { default as Footer } from "./foooter/Footer"
export { default as Silder } from "./slider/Slider"
export { default as History } from "./history/History"
export { default as Product } from "./product/product"
export { default as CountDown } from "./countDown/CountDown"
export { default as Input } from "./input/Input"
export { default as Button } from "./button/Button"
export { default as Loading } from "./loading/Loading";
export { default as Breadcrumbs } from "./breadcrumbs/Breadcrumbs"
export { default as ProductSimilar } from "./productSimilar/ProductSimilar";
export { default as Quantity } from "./quantity/Quantity";
