export { default as Header } from "./header/header"
export { default as Footer } from "./foooter/Footer"
export { default as Silder } from "./slider/Slider"
export { default as History } from "./history/History"
export { default as Product } from "./product/product"
export { default as CountDown } from "./countDown/CountDown"
export { default as Input } from "./input/Input"
export { default as Button } from "./button/Button"
export { default as Loading } from "./loading/Loading";
export { default as Breadcrumbs } from "./breadcrumbs/Breadcrumbs"
export { default as ProductSimilar } from "./productSimilar/ProductSimilar";
export { default as Quantity } from "./quantity/Quantity";
export { default as DescriptionProduct } from "./discriptionProduct/DiscriptionProduct";
export { default as FilterPro } from "./FilterPro/FilterPro";
export { default as InputSelect } from "./inputSelect/InputSelect";
export { default as PaginationCustom } from "./pagination/Pagination";
export { default as Adminsibar } from "./adminSibar/Adminsibar";
export { default as MemberSibar } from "./MemberSibar/MemberSibar";
export { default as QuickView } from "./quickView/QuickView";

